Добавит разметку Главной страницы и Каталога
wrgraff/535607-gllacy-36 pull request #2
Opened 2023-04-17 18:18 UTC by Elijah-Djilin

2023-04-18 17:29 UTC, wrgraff requested changes
Отлично получилось, поэтому я немного попридирался даже.
Прилагаю [правила, по которым делаю ревью](https://telegra.ph/Pravila-revyu-04-02). Стоит изучить, чтобы всякие смайлики и прочие нюансы не сбивали с толку )

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +  <link rel="stylesheet" href="style.css">
Нужно иметь ввиду, что далее у нас стили будут лежать в папке `css`.
Давай сразу перенесем их в такую папку + нужно поправить пути в html-файлах и в самом CSS (подключение шрифтов)

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +    <!-- ==== LOGO ==== -->
На мой вкус, такие комментарии излишни. Комментарий нужен, чтобы прояснить какую-то информацию, которой не видно по коду. Например, если у нас верстка сделана без js, могут быть комментарии о том, какие классы должны меняться при действиях на странице.

Здесь — сомнительная информация =)
То, что это лого, хорошо видно исходя и из `<a class="logo">`

Но может они у тебя больше для ориентирования в коде, конечно. Тут уже вкусовщина

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <!-- возможно, модификатор лучше повесить на ссылку -->
Я бы предпочел на элементе. В БЭМ, если не сходить с ума, допустимо стилизовать элемент от модификатора другого элемента (в рамках одного блока, разумеется)

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <!-- возможно, модификатор лучше повесить на ссылку -->
Кстати, если есть комментарии, которые хорошо бы разобрать на ревью, лучше не добавлять в сам код. Сам код должен содержать только те комментарии, которые не будут лишним в продакшене.
Вопросам и закомментированному коду лучше в прод не попадать.

Вопрос можно оставить в пул-реквесте, так же, как их оставляю я — то есть самому комментировать свой пул-реквест

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <a class="main-nav__link" href="/delivery">Доставка и оплата</a>
Не очень понятная ссылка. Если мы хотим имитировать ссылку на другую страницу, то она должна быть такого же формата, что и рабочая ссылка (как каталог), то есть `href="delivery.html`.

Ну или мы можем вовсе не запариваться с несуществующими страницами и всем им ставить `#`. Что тоже может быть удобно, так как случайный клик при тестировании верстки не приведет к переходу в никуда.

> Ниже применяется подход с `#`. нужно обязательно определиться как мы делаем ссылки на страницы, которых нет и придерживаться одного подхода.

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +      <ul class="main-nav--list">
Класс модификатора применен без класса блока.

Модификатор — это такая штука, которая берет готовый элемент или блок, и что-то в нем меняет. Например, у нас есть блок `button`. Он по умолчанию имеет какой-то размер, а нам нужен такой же, только побольше: там шрифт чуть крупнее и отступы. Мы создаем модификатор, который добавит именно эти стили: `button--large`.
Тогда получается, обычный элемент будет выглядеть так:

```html
<button class="button" type="button">Кнопка</button>
```

А если нам нужна будет кнопка побольше, то мы добавим модификатор к ней же, вторым классом:

```html
<button class="button button--large" type="button">Кнопка</button>
```

Сам по себе модификатор работать не может, он применяется к уже существующему блоку или элементу. Он не самостоятелен, а только меняет существующие стили.

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <a class="main-nav__link main-nav__link--bold" href="tel:+78005558628">+7 800 555-86-28</a>
Нет особой ценности в сохранении того же класса `main-nav`, который применен в основном меню.
Эти ссылки отличаются друг от друга весьма заметно:
<img width="440" alt="изображение" src="https://user-images.githubusercontent.com/37917037/232848579-c36b0cdf-7719-46ca-b29b-fe5ef0788ec6.png">
<img width="463" alt="изображение" src="https://user-images.githubusercontent.com/37917037/232848615-309bc306-77f0-4416-98fe-12225fe44a5b.png">

Все же будет проще задать им изначально разные стили, чем пытаться их модифицировать и переделать один элемент в другой.

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +      <!-- секция с популярными товарами есть, подарки тоже есть. Может специальные предложения, или можно сделать просто div без заголовка -->
"Карусель" — это конечно скорее ответ как интерфейсно представлен контент. А заголовок должен описывать контент с точки зрения смысла, и да, тут не очень то понято в чем идея этих мороженок. Был бы у нас дизайнер или проджект-менеджер — мы бы спросили у них.

Так как их нет, можно придумать что-то свое, из головы. Может, это новинки, может еще что-то.
От `section` отказываться не хочется, он тут логически очень уместно выглядит

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +    <section class="carousel">
Где-то должен был быть заголовок первого уровня, без него нельзя

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <a class="carousel__btn" href="#">Заказать</a>
Все кнопки более-менее одинаковы, хорошо бы для них завести отдельный класс, например `btn`:
```suggestion
          <a class="carousel__btn btn" href="#">Заказать</a>
```

По БЭМу очень хорошо ложится такая логика миксования элемента и блока:
`carousel__btn` — отвечает за положение в сетке, отступы и прочее взаимодействие с другими элементами блока `carousel`
`btn` — отвечает за оформление самой кнопки: цвет, шрифт, внутренние отступы и прочее

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          </button>
На самом деле, на практике кнопки типа "Добавить в корзину" делают ссылками.

Потому что это для интернет-магазина критическая функциональность, и нужно подстраховаться и сделать так, чтобы кнопка работала без js.

Прямо в адрес ссылки может быть включен запрос с добавлением товара в корзину. При переходе на этот адрес товар добавляется в корзину и потом срабатывает переадресация обратно, где грузится страница с уже обновленной корзиной. Будет работать с перезагрузкой страницы, но зато будет работать всегда: ссылку в html-коде сломать крайне сложно.

А потом уже поверх пишется js, который останавливает переход по ссылке, сам вместо него делает запрос, получает ответ, а затем обновляет состояние корзины.

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +        </li>
Как правило, карточка имеет ссылку на страницу самого товара

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <!-- вместо .gifts__item можно использовать .gift -->
Может быть. Но пока вроде бы блок `gifts` не настолько раздулся, чтобы выделить айтемы в отдельный блок

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +      </p>
Хорошее разделение на видимый заголовок и заголовок "по существу"

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +    <!-- или как section со скрытым заголовоком h2, в карточках будут h3 и классы строить от .blog -->
А я не вижу большой проблемы в том, чтобы сделать и общий `section` с заголовком и оставить внутри элементы как `article` с заголовками 3-го уровня.
Одно другому не противоречит, а структура по заголовкам будет как-то поприятнее

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <input name="email" type="text" placeholder="email@example.com" required>
У инпута обязательно должен быть `<label>`

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <button type="submit">Отправить</button>
А чего они такие сиротливые без классов остались )

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +        <h2 class="page__title--sm blog-article__title">
Класс модификатора `page__title--sm` применен без класса элемента.

Вообще, чтобы проверить чисто технические моменты по БЭМ (а заодно и по структуре заголовков) можно воспользоваться [инструментом от Йоксель](https://yoksel.github.io/html-tree/).

Там еще есть недочет по БЭМу (формально): попробуй воспользоваться и найти его =)

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +        <!-- ссылка, скорее всего, будет вокруг блока. если она нужна -->
Нужна, пускай будет

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +              <!-- если со стилизацией date будут проблемы то просто text -->
Проблемы точно будут, правда я на проверках обычно игнорирую эти расхождения, так как для пользователя будет лучше чтобы поле было с типом "дата".
Это важнее, чем совпадение с макетом, потому что принесет больше удобства

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +              </div> -->
Тут стоит сделать 2 вещи:
- раскомментировать подсказку, так как это код, который должен быть на странице;
- придумать какое-нибудь описание на свой вкус, просто похожее на подобное описание (да хоть у ChatGPT спросить)

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +        </button>
Есть такое понятие, как [[прогрессивное улучшение](https://htmlacademy.ru/blog/boost/frontend/progressive-enhancement)](https://htmlacademy.ru/blog/boost/frontend/progressive-enhancement) (progressive enhancement).

> Очень коротко: если не может сработать самое удобное решение, должно сработать более простое и надежное, которое позволит воспользоваться функциональностью.

Для кнопок, вызывающих появление модального окна, лучше сделать ссылку, чтобы при отвалившемся JS произошел переход на страницу, где эта форма есть отдельно.

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <!-- "/" чтобы валидатор не ругался -->
По-моему, как есть уже хорошо. Не сказал бы, что есть причина, по которой одна из альтернатив была бы намного лучше

2023-04-18 17:29 UTC, wrgraff commented on index.html
> +          <a class="footer__link footer__link--has-icon" href="#">Для поставщиков</a>
А какой `icon`?
Формулировка `has-icon` говорит будто бы о том, что еще и отдельно где-то должно определяться что за иконка.
Ну или же она какая-то самоочевидная. Но я бы не сказал так )

2023-04-18 17:29 UTC, wrgraff commented on catalog.html
> +
Что-то на странице каталога и докопаться не к чему =)

2023-04-19 11:15 UTC, Elijah-Djilin commented on index.html
> +    <!-- ==== LOGO ==== -->
да, они как плейсхолдеры когда блока ещё нет и для навигации

2023-04-19 11:26 UTC, Elijah-Djilin commented on index.html
> +    <section class="carousel">
Он был, но куда-то пропал

2023-04-19 11:28 UTC, Elijah-Djilin commented on index.html
> +      <!-- секция с популярными товарами есть, подарки тоже есть. Может специальные предложения, или можно сделать просто div без заголовка -->
Да, новинки подойдёт отлично

2023-05-05 20:03 UTC, wrgraff commented on catalog.html
> +          <input class="input search__field" id="search" type="search" name="search" placeholder="Поиск по сайту" required>
До этого момента при миксовании блока и элемента сперва шел класс элемента, а затем — класс блока.
Тут наоборот.

Разумеется, сам порядок не принципиален, но принципиально чтобы он в проекте всегда был один

2023-05-05 20:03 UTC, wrgraff commented on catalog.html
> +          <fieldset class="sign-in__fieldset">
А зачем нам филдсет?
Чтобы использовать легенду как заголовок?
Интересное решение =) Правда, тут скорее вся форма про личный кабинет... С другой стороны, а какая у нас альтернатива. Так тоже интересно

2023-05-05 20:03 UTC, wrgraff commented on catalog.html
> +          </ul>
Не слишком ли для 2 ссылок список?
Но тут тебе решать

2023-05-05 20:03 UTC, wrgraff commented on catalog.html
> +          <!-- <span>Нет товаров</span> -->
Лучше конечно не делать закоментированный код...

2023-05-05 20:03 UTC, wrgraff commented on catalog.html
> +          <p class="title title--xs cart__sum">Итого: <span>790</span> ₽</p>
Хочется в разметке в другом порядке поставить )

2023-05-05 20:03 UTC, wrgraff commented on index.html
> +    <h1 class="sr-only">HTML Academy: Магазин Глейси</h1>
А почему `HTML Academy` то =)
HTML Academy тут типа разработчик как бы. Вряд ли тут был бы такой заголовок

2023-05-05 20:03 UTC, wrgraff commented on index.html
> +          </a>
Как-то странновато, что ссылка на описании, а не на названии товара

2023-05-05 20:03 UTC, wrgraff commented on index.html
> -          <a class="gifts__btn" href="#">Хочу подарок</a>
А куда это секция делась с подарками? О_о

2023-05-05 20:03 UTC, wrgraff commented on index.html
> +        <h2 class="title title--md blog-article__title">
Тут должен быть же заголовок 3-го уровня

2023-05-05 20:03 UTC, wrgraff commented on index.html
> +          <label class="sr-only" for="subscribe-email">Укажите адрес эл. почты</label>
Писать подробнее это хорошо, но обычно лейблы ведь не так звучат )
Кажется, более привычно будет просто "Электронная почта"

2023-05-05 20:03 UTC, wrgraff commented on index.html
> +        <fieldset class="feedback__fieldset">
Филдсет или не нужен, или должен содержать `legend`

2023-05-05 20:03 UTC, wrgraff commented on index.html
> +        </button>
Во я ссылку то сломал

2023-05-05 20:11 UTC, wrgraff requested changes
Еще чуток правок накидал

2023-05-07 14:10 UTC, wrgraff approved these changes

2023-05-07 14:10 UTC, wrgraff commented on index.html
> +              <legend class="sr-only">Форма обратной связи</legend>
Ну вот в принципе по легенде видно, что группа полей здесь не так уж полезна.
Группы полей все-таки логично смотрятся, когда полей много и их удобно по этим самым группам делить. А когда она одна, то странно выглядит

2023-05-07 14:10 UTC, wrgraff commented on index.html
> +        <div class="feedback">
С section'ом то получше было, это же вполне внятный по смыслу блок

2023-05-07 14:10 UTC, merged